GET http://localhost:9999/api/users

###

DELETE  http://localhost:9999/api/carts/1


###
GET  http://localhost:9999/api/carts
###

GET http://localhost:9999/api/products?_sort=id&_order=desc

###
GET http://localhost:9999/api/products?name_like=áo

###
GET http://localhost:9999/api/products